### ISSUE TITLE
spellCheckHandler.attachToInput breaks on electron 5.0.0

### ISSUE THREAD

**Issue by robsonhermes** [electron-userland/electron-spellchecker#144]
Hello

Starting from Electron 5.0.0, the method `spellCheckHandler.attachToInput` breaks with:

![image](https://user-images.githubusercontent.com/26451017/56961258-9d7a3400-6b53-11e9-97ef-36d220dc09fc.png)

I guess this happens cause parameters of method `webFrame.setSpellCheckProvider` changed in version 5.0.0 -> [link](https://electronjs.org/docs/api/web-frame#webframesetspellcheckproviderlanguage-provider).

**Comment by smithalan92** [comment]
This is still an issue in `2.0.4`

Looks like its a bigger issue than the `setSpellCheckProvider` signature changing though. 

Correcting the passed params [here](https://github.com/electron-userland/electron-spellchecker/blob/master/src/spell-check-handler.js#L144) and [here](https://github.com/electron-userland/electron-spellchecker/blob/master/src/spell-check-handler.js#L304) , solves the processing error, but introduces a new error

![image](https://user-images.githubusercontent.com/17986423/58958043-e435fc00-8799-11e9-93f4-b0e05b5ee4a1.png)

**Comment by mlalkaka** [comment]
I'm working on fixing this. Will have a fork + PR up soon.

**Comment by mlalkaka** [comment]
@robsonhermes and @smithalan92, I've created a branch and PR to fix this. If you're still interested, could you try the change in your environments and/or provide feedback? The branch is [mlalkaka/electron-spellchecker](https://github.com/mlalkaka/electron-spellchecker).

**Comment by robsonhermes** [comment]
@mlalkaka  will try that in my first open slot and update you here. Many thanks!

**Comment by smithalan92** [comment]
Thats great @mlalkaka , I have that a test using Electron v5 and it works nicely 👌 Hopefully @felixrieseberg will have some time to approve the PR and deploy a new version

**Comment by felixrieseberg** [comment]
Fixed and released as 2.1.0 🙇

**Comment by robsonhermes** [comment]
Still not working for me.

Could anyone please tell me if you had the same problem?

https://github.com/robsonhermes/electron-spellchecker-test
npm install && .\node_modules\.bin\electron-rebuild.cmd

results in the error I posted in my last msg.

**Comment by smithalan92** [comment]
Your example works fine for me @robsonhermes ( I'm on MacOS though )

**Comment by robsonhermes** [comment]
Just tried on Linux (Ubuntu). fails with the same error. But I guess it´s not related to this fix.
Will open a separate issue.

Thanks for trying it out, @smithalan92

**Comment by mlalkaka** [comment]
@robsonhermes, sorry for the late reply here. I've been trying to repro
this on Windows, but have been having unrelated troubles with my Windows
PC. I'll give this another try later today.

**Comment by robsonhermes** [comment]
No problem @mlalkaka , I am the one to thank you for your efforts on fixing compatibility with Electron 5. 

I believe this is a separate problem, thus decided to raise another issue to keep the discussion separated. Please see [151](https://github.com/electron-userland/electron-spellchecker/issues/151).
